---
hmc_host: 10.11.12.13

cpc_name: P0001234
partition_name: zhmc-part-1
crypto_adapter_name: Crypto 0124 A13B-12

hba_name: hba-1
hba_adapter_name: FCP 0108 A13B-03
hba_adapter_port: 0

nic_name: nic-1
nic_adapter_name: OSD 0128 A13B-13
nic_adapter_port: 0

vfunction_name: vfunction-1
vfunction_adapter_name: zEDC 0144 A13B-21
